# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_RSingleRust_wrappers", use_symbols = TRUE, package_name = "RSingleRust")

#' @usage NULL
#' @useDynLib RSingleRust, .registration = TRUE
NULL

#' temp function
#' @export
read_matrix <- function(matrix, cells, genes) invisible(.Call(wrap__read_matrix, matrix, cells, genes))

# nolint end
