# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_RSingleRust_wrappers", use_symbols = TRUE, package_name = "RSingleRust")

#' @usage NULL
#' @useDynLib RSingleRust, .registration = TRUE
NULL

#' read dense matrix as an in-memory AnnData
#' @export
read_matrix_dense <- function(matrix, cells, genes) invisible(.Call(wrap__read_matrix_dense, matrix, cells, genes))

#' temp function
#' @export
read_matrix_hdf5 <- function(file_path, group_path) .Call(wrap__read_matrix_hdf5, file_path, group_path)

#' temp function
#' @export
update_S4 <- function(obj, slot) .Call(wrap__update_S4, obj, slot)

#' temp function
#' @export
sparse_check_s4 <- function(obj) .Call(wrap__sparse_check_s4, obj)

#' temp function
#' @export
get_qc_metrics <- function(obj, slot, cells, genes) .Call(wrap__get_qc_metrics, obj, slot, cells, genes)

# nolint end
